# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        # You may pin to the exact commit or the version.
        # uses: britannio/action-install-flutter@a486b7e3148e54a76390d849100b9dee819ff810
        uses: britannio/action-install-flutter@v1.1
        with:
          # The channel/version of Flutter to be used e.g., beta or 2.0.0
          version: stable

      - name: Install dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: flutter analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: flutter test

      - name: Build web
        run: flutter build web
      - name: Deploy to GitHub pages
        # run: sh deploy.sh
        run: |
          flutter build web --release --base-href //auto_deploy_flutter_web_to_ghpages/
          sed -i 's/\/auto_/auto_/g' build/web/index.html
          cp -r build/web/* docs
          git config user.name "Jonas Reycian"
          git config user.email "jonasreycian@gmail.com"
          git add .
          git commit -m 'Deploy'
          git push origin HEAD --force
          rm -r build
      #   env:
      #    USER_NAME: ${{ secrets.USER_NAME }}
      #    USER_EMAIL: ${{ secrets.USER_EMAIL }}
  
  deploy-to-web:
    name: Deploy to GitHub Pages 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub pages
        run: |
          flutter build web --release --base-href //auto_deploy_flutter_web_to_ghpages/
          sed -i 's/\/auto_/auto_/g' build/web/index.html
          cp -r build/web/* docs
          git config user.name "Jonas Reycian"
          git config user.email "jonasreycian@gmail.com"
          git add .
          git commit -m 'Deploy'
          git push origin HEAD --force
          rm -r build
