# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
        with:
          version: stable
      - run: flutter doctor -v
        
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build Flutter Web
        run: flutter build web --release --base-href //auto_deploy_flutter_web_to_ghpages/

      - name: Deploy to GitHub pages
        run: |
          sed -i 's/\/auto_/auto_/g' build/web/index.html
          cp -r build/web/* docs
          git config user.name $USER_NAME
          git config user.email $USER_EMAIL
          git add .
          git commit -m 'Deploy'
          git push origin HEAD --force
          rm -r build
        env:
         USER_NAME: ${{ secrets.USER_NAME }}
         USER_EMAIL: ${{ secrets.USER_EMAIL }}
